### ISSUE TITLE
Static Featured speakers

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/drupalcampcebu2017#22]
**Context**
The design implements a section called "Featured speakers".

**Implementation**
Use a placeholder for now. We are not yet sure who will be the final featured speakers.
Future plans could include an animated gif of each speaker.

<img width="825" alt="screenshot 2017-10-20 13 04 37" src="https://user-images.githubusercontent.com/1465207/31805911-2600b192-b597-11e7-9aeb-150eb43b700d.png">

**Comment by Luukyb** [comment]
Hi @rannynavarro ,
@leolandotan started branch (Ticket #27 ) using Jekyll for the static site. If this gets merged, you will have to start using Jekyll on your local too.
Thanks!

**Comment by rannynavarro** [comment]
@Luukyb 
I have updated my local by installing jekyll. I have re-cloned the site and it's now using jekyll. Will apply my current changes after reviewing the new structure in relation to jekyll.

**Comment by Luukyb** [comment]
<img width="833" alt="screenshot 2017-11-11 16 12 51" src="https://user-images.githubusercontent.com/1465207/32687612-44fae70a-c6fb-11e7-9b65-a7b8d8c30de8.png">

**Comment by Luukyb** [comment]
Merged and pushed to master.
