### ISSUE TITLE
Static Update Sponsors

### ISSUE THREAD

**Issue by marychris** [Luukyb/drupalcampcebu2017#23]
A.
- Add Srijan logo in the Gold sponsor region right below the 'register' button.
- Update Promet Source logo to use the square one. (See image below.)
![prometsourcesqaure](https://user-images.githubusercontent.com/8597102/31807883-309eaa94-b5a3-11e7-9107-45873c23bc20.png)

B.
- Right below the featured speakers;
  -  Add the sponsors: GOLD (Srijan, Promet Source), SILVER (Pantheon)
  -  Below should be an 'arrow down' icon -- when clicked will show a dropdown of the COFFEE sponsor (SkyRock IT).

**Comment by RaymondAngana** [comment]
Hi @marychris, @Luukyb 

Good day!

I pushed this PR to address this issue.
https://github.com/Luukyb/drupalcampcebu2017/pull/36

Here's how it looks on my end:
![image](https://user-images.githubusercontent.com/1076332/31871266-8f842860-b7e5-11e7-87f6-9b142709a2fc.png)

I do have some concerns:
1. The "blue" colored font on Prometsource doesn't seem to look good on a dark background. I'm suggesting we change this to WHITE. I do however need to know what font is this? Arial, Tahoma or Verdana?

2. The Srijan logo is a bit bigger than Prometsource. I think we need to make all logo of same size (and twice as big for mobile retina display). Can you suggest an optimal width/height for these logo and will update the images.

3. Can you please clarify any other logo to use for Srijan/Pantheon if the one I uploaded is wrong?

4. Please clarify on the B.2 instruction above about having an "arrow". Can you please clarify on how this is supposed to be shown? I'm a bit lost.

**Comment by Luukyb** [comment]
Thanks @RaymondAngana 
I did some changes and added more logos.
This is merged now.

**Comment by Luukyb** [comment]
Part B of this ticket is not completed.

**Comment by Luukyb** [comment]
WIP on branch: feature-23-sponsor-page
