### ISSUE TITLE
Static Session Schedule

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/drupalcampcebu2017#24]
**Context**
Speakers list is pending final confirmation.

**Implementation**
On the static, implement a template for the schedule.
Use lorem ipsum for now.
It should be similar to: https://2015.drupalcebu.org/sessions

**Comment by mtem27** [comment]
PR for schedule.html page, https://github.com/Luukyb/drupalcampcebu2017/pull/40

Pending work: CSS Styling for schedule.html page

**Comment by Luukyb** [comment]
<img width="1227" alt="screenshot 2017-11-12 16 08 36" src="https://user-images.githubusercontent.com/1465207/32697865-2191d6a4-c7d5-11e7-94ea-4d26a5606de3.png">

**Comment by Luukyb** [comment]
Merged. Thanks for the initial layout and markup @mtem27 !
