### ISSUE TITLE
Static Venue Information

### ISSUE THREAD

**Issue by Luukyb** [Luukyb/drupalcampcebu2017#25]
**Context**
We need a map displaying the venue.

**Implementation**
Right before the footer, put a title "Venue" with HTML id "venue". Link in the menu Venue, should be pointing to "#venue". 
Implement a google map with the location of CIT University.

**Comment by Luukyb** [comment]
PR merged from @leolandotan.
Thanks!

**Comment by Luukyb** [comment]
Re-opening this issue. Since we are using Jekyll, it would be best to have the link in the menu and this will open a new page with:
Logo of CIT University
Description of the venue
Jeepneys going to CIT University
Map

For the map and the menu item, please re-use what @leolandotan did. It is commented out in the template. You need to change the menu link to go to the venue page, instead of #venue. Some SASS code can be re-used too.

Thanks

**Comment by leolandotan** [comment]
Hi @Luukyb any details that I can use like for the description of the venue and the content placements?

Here are initial results:
![dc2017-venue-initial-content](https://user-images.githubusercontent.com/3686017/32135304-3040f024-bc2f-11e7-8c25-ac63a41bac8d.png)

CIT description taken from Wikipedia.

What are your thoughts on this?

**Comment by Luukyb** [comment]
Hi @leolandotan ,
Looks great, just few comments:
- More space after the main title "Venue"
- More space on top and bellow title "Address"
- Link to their website in a new tab on their logo
- Link to their website in a new tab after the description text

Let me know if any issues,
Thanks!
Luc

**Comment by Luukyb** [comment]
Merged and pushed to master.
Thanks Lei !
