### ISSUE TITLE
Fix homepage keynote speaker background image

### ISSUE THREAD

**Issue by leolandotan** [Luukyb/drupalcampcebu2017#28]
Use `background-size: cover;` for the image for better output on any screen size.

## Issue
<img width="1261" alt="dccebu2017-ticket-28-issue" src="https://user-images.githubusercontent.com/3686017/31854498-eac4fad4-b6cc-11e7-9973-23978082869b.png">

**Comment by Luukyb** [comment]
Merged, thanks!
