### ISSUE TITLE
Fix logo section dimension in Firefox

### ISSUE THREAD

**Issue by leolandotan** [Luukyb/drupalcampcebu2017#42]
## Issue
![screenshot-2017-10-28 drupalcamp cebu 2017 november 25 2017](https://user-images.githubusercontent.com/3686017/32135127-487daf86-bc2c-11e7-83db-e461976c0cd7.png)

Fix this to make it consistent on how it's displayed in Google Chrome.

**Comment by Luukyb** [comment]
Merged @leolandotan, was there something more for this issue?

**Comment by leolandotan** [comment]
@Luukyb I think there isn't. We're all good on this issue. Thanks!
