### ISSUE TITLE
Link hover state is black and makes the text unreadable

### ISSUE THREAD

**Issue by leolandotan** [Luukyb/drupalcampcebu2017#54]
![issue-54-black-link-text-on-hover](https://user-images.githubusercontent.com/3686017/32931301-71f2ff02-cb9e-11e7-82b2-195ba124fa29.jpg)

## Proposed solution
* Keep the normal link state as bold without underline
* Change the hover link state to be underlined

**Comment by Luukyb** [comment]
Merged, thanks @leolandotan
